### ISSUE TITLE
关于蒙特卡洛模拟it's about Monte Carlo simulation

### ISSUE THREAD

**Issue by tangeroo** [dizhu-gis/cedgan-interpolation#1]
您好，我发现您们的论文中提到用蒙特卡洛方法来裁剪图像，从而产生数据。我想请问一下用这种方法和直接裁剪有什么区别？如果会影响到对抗网络的运行，是否可以提供一下这个裁剪工具。我初入这一块，如有不合理的请求还请见谅,谢谢~
Hello,sorry to bother. In your paper,Monte Carlo simulation is used to crop images to titiles.May I ask the difference between this method and cropping directly?If the data processing impacts the function of the network, I am wondering if you can provide me this cropping tool.
I'm fresh in this filed,forgive me for any unreasonable request,thank you.

**Comment by dizhu-gis** [comment]
Hi tangeroo,

Monte-Carlo Simulation is selected because we wanted the cropped DEM images to have no repetition. The crop has no significant influence on the model performance as long as your input images contain enough variation. 
The key is to make sure that CEDGAN achieves spatial interpolation by capturing those spatial structural features rather than memorizing/overfitting images.

For example, you can use any "random" package in python (https://pythonprogramming.net/monte-carlo-simulator-python/) to help you generate your own input data.

Best

**Comment by tangeroo** [comment]
Thanks a loooot!
